version: "3.9"
services:
  db:
      image: "mcr.microsoft.com/mssql/server:2022-latest" # image: mcr.microsoft.com/azure-sql-edge for M1
      container_name: quickappdb 
      networks:
        static-network:
           ipv4_address: 172.28.0.2
      environment:
        - SA_PASSWORD=Abcdef@.123456 # Check in your connectstring appsettings.json
        - ACCEPT_EULA=Y
  app:
      image: "tiennp/quick-app"
      networks:
        static-network:
          ipv4_address: 172.28.0.4
      container_name: angular_app
      depends_on:
        - db
      ports:
        - "80:5000"  
        - "443:5001"
      environment:
        - ConnectionStrings:DefaultConnection=Server=172.28.0.2;Database=QuickApp;User ID=sa;Password=Abcdef@.123456
        - ASPNETCORE_URLS=https://+:5001;http://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.0.0/24
          gateway: 172.28.0.255
